[profile.ci]
fuzz-runs = 10_000

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['DelegationGuard', 'DelegationOwner', 'DelegationRecipes', 'DelegationWalletFactory', 'DelegationWalletRegistry']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config